version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  kaggle-data-api:
    build:
      context: .
      dockerfile: services/kaggle-data-api/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://test_user:test_password@postgres:5432/test_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      NODE_ENV: test
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
