version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  kaggle-data-api:
    build:
      context: .
      dockerfile: services/kaggle-data-api/Dockerfile
    environment:
      PORT: 3001
      HOST: 0.0.0.0
      NODE_ENV: development
      # Service expects DB_* vars (see database plugin)
      DATABASE_URL: postgresql://test_user:test_password@postgres:5432/test_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      LOG_LEVEL: info
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3001/health/live',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_test_data:
