apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kaggle-data-pvc.fullname" . }}
  labels:
    {{- include "kaggle-data-pvc.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
    {{- with .Values.storage.additionalAccessModes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumeMode: {{ .Values.volumeMode | default "Filesystem" }}
  {{- with .Values.dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
