{{- define "job.secret" -}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "job.fullname" . }}
  labels:
    {{- include "job.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
{{- end }}
