# Values for production environment

storage:
  # Use cloud provider's high-performance storage class
  # AWS: gp3, io1, io2
  # GCP: standard-rwo, pd-ssd
  # Azure: managed-premium
  storageClassName: gp3 # Change based on your cloud provider

  # Production requires ReadWriteMany for high availability
  accessMode: ReadWriteMany

  # Production size with buffer for growth
  size: 20Gi

# Labels for production environment
labels:
  app: kaggle-data
  component: storage
  managed-by: helm
  environment: production

annotations:
  description: 'Production storage for Kaggle datasets'
  # Add cloud-specific annotations
  # AWS example:
  # volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  # encrypted: "true"
