{{- define "service.secret" -}}
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
{{- end }}
